#SPDX-License-Identifier: MIT
version: '3'
services:
  database:
    build:
      context: ./
      dockerfile: util/docker/database/Dockerfile
    image: augurlabs/augur:database-dev
    restart: unless-stopped
    ports:
      - 5434:5432
